[package]
name = "common"
version = "0.1.0"
edition = "2024"

[features]
default = []
sea-orm = ["dep:sea-orm"]

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
config.workspace = true
rand.workspace = true
sea-orm = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
utoipa.workspace = true
hex.workspace = true
sha2.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile = "3"
