[package]
name = "test-plugin"
version = "0.1.0"
edition = "2024"

[dependencies]
extism-pdk = "1.4.1"
sea-query = "1.0.0-rc.30"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"

[workspace]

[lib]
crate-type = ["cdylib"]
