name = "test-plugin"
version = "0.1.0"
description = "A demo plugin"

[server]
entry = "main.wasm"
permissions = ["logger", "storage", "sql"]

[[server.routes]]
method = "POST"
path = "/{name}/greet"
handler = "greet"

[[server.routes]]
method = "POST"
path = "/post-message"
handler = "post_message"

[web]
root = "app"
entry = "index.js"
